#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# RUTAS DE CONTROLADOR: USUARIO #

user:
    path: /user
    controller: App\Controller\UserController::index
    methods: [POST]

createUser:
    path: /createUser
    controller: App\Controller\UserController::createUser
    methods: [POST]

login:
    path: /login
    controller: App\Controller\UserController::login
    methods: [POST]

updateUser:
    path: /updateUser
    controller: App\Controller\UserController::updateUser
    methods: [PUT]


# RUTAS DEL CONTROLADOR: VIDEO #

video:
    path: /video
    controller: App\Controller\VideoController::index